import { z } from "zod";
import type { ToolDefinition } from "../index.js";

// x86 register database
interface RegInfo {
	name: string;
	size: number; // bits
	family: string; // e.g. "rax" (canonical 64-bit name)
	encoding: number; // register encoding 0–7 (+ REX.B/R/X for extended)
	type:
		| "gpr"
		| "segment"
		| "control"
		| "debug"
		| "xmm"
		| "ymm"
		| "zmm"
		| "mmx"
		| "st"
		| "flags"
		| "ip";
	parts?: string[]; // sub-registers
	aliases?: string[]; // all aliases (incl. self)
}

const REGISTERS: Record<string, RegInfo> = {
	// 64-bit GPRs
	rax: {
		name: "rax",
		size: 64,
		family: "rax",
		encoding: 0,
		type: "gpr",
		parts: ["rax", "eax", "ax", "al", "ah"],
		aliases: ["rax", "eax", "ax", "al", "ah"],
	},
	rcx: {
		name: "rcx",
		size: 64,
		family: "rcx",
		encoding: 1,
		type: "gpr",
		parts: ["rcx", "ecx", "cx", "cl", "ch"],
		aliases: ["rcx", "ecx", "cx", "cl", "ch"],
	},
	rdx: {
		name: "rdx",
		size: 64,
		family: "rdx",
		encoding: 2,
		type: "gpr",
		parts: ["rdx", "edx", "dx", "dl", "dh"],
		aliases: ["rdx", "edx", "dx", "dl", "dh"],
	},
	rbx: {
		name: "rbx",
		size: 64,
		family: "rbx",
		encoding: 3,
		type: "gpr",
		parts: ["rbx", "ebx", "bx", "bl", "bh"],
		aliases: ["rbx", "ebx", "bx", "bl", "bh"],
	},
	rsp: {
		name: "rsp",
		size: 64,
		family: "rsp",
		encoding: 4,
		type: "gpr",
		parts: ["rsp", "esp", "sp", "spl"],
		aliases: ["rsp", "esp", "sp", "spl"],
	},
	rbp: {
		name: "rbp",
		size: 64,
		family: "rbp",
		encoding: 5,
		type: "gpr",
		parts: ["rbp", "ebp", "bp", "bpl"],
		aliases: ["rbp", "ebp", "bp", "bpl"],
	},
	rsi: {
		name: "rsi",
		size: 64,
		family: "rsi",
		encoding: 6,
		type: "gpr",
		parts: ["rsi", "esi", "si", "sil"],
		aliases: ["rsi", "esi", "si", "sil"],
	},
	rdi: {
		name: "rdi",
		size: 64,
		family: "rdi",
		encoding: 7,
		type: "gpr",
		parts: ["rdi", "edi", "di", "dil"],
		aliases: ["rdi", "edi", "di", "dil"],
	},
	r8: {
		name: "r8",
		size: 64,
		family: "r8",
		encoding: 8,
		type: "gpr",
		parts: ["r8", "r8d", "r8w", "r8b"],
		aliases: ["r8", "r8d", "r8w", "r8b"],
	},
	r9: {
		name: "r9",
		size: 64,
		family: "r9",
		encoding: 9,
		type: "gpr",
		parts: ["r9", "r9d", "r9w", "r9b"],
		aliases: ["r9", "r9d", "r9w", "r9b"],
	},
	r10: {
		name: "r10",
		size: 64,
		family: "r10",
		encoding: 10,
		type: "gpr",
		parts: ["r10", "r10d", "r10w", "r10b"],
		aliases: ["r10", "r10d", "r10w", "r10b"],
	},
	r11: {
		name: "r11",
		size: 64,
		family: "r11",
		encoding: 11,
		type: "gpr",
		parts: ["r11", "r11d", "r11w", "r11b"],
		aliases: ["r11", "r11d", "r11w", "r11b"],
	},
	r12: {
		name: "r12",
		size: 64,
		family: "r12",
		encoding: 12,
		type: "gpr",
		parts: ["r12", "r12d", "r12w", "r12b"],
		aliases: ["r12", "r12d", "r12w", "r12b"],
	},
	r13: {
		name: "r13",
		size: 64,
		family: "r13",
		encoding: 13,
		type: "gpr",
		parts: ["r13", "r13d", "r13w", "r13b"],
		aliases: ["r13", "r13d", "r13w", "r13b"],
	},
	r14: {
		name: "r14",
		size: 64,
		family: "r14",
		encoding: 14,
		type: "gpr",
		parts: ["r14", "r14d", "r14w", "r14b"],
		aliases: ["r14", "r14d", "r14w", "r14b"],
	},
	r15: {
		name: "r15",
		size: 64,
		family: "r15",
		encoding: 15,
		type: "gpr",
		parts: ["r15", "r15d", "r15w", "r15b"],
		aliases: ["r15", "r15d", "r15w", "r15b"],
	},
	// 32-bit views
	eax: {
		name: "eax",
		size: 32,
		family: "rax",
		encoding: 0,
		type: "gpr",
		parts: ["eax", "ax", "al", "ah"],
		aliases: ["rax", "eax", "ax", "al", "ah"],
	},
	ecx: {
		name: "ecx",
		size: 32,
		family: "rcx",
		encoding: 1,
		type: "gpr",
		parts: ["ecx", "cx", "cl", "ch"],
		aliases: ["rcx", "ecx", "cx", "cl", "ch"],
	},
	edx: {
		name: "edx",
		size: 32,
		family: "rdx",
		encoding: 2,
		type: "gpr",
		parts: ["edx", "dx", "dl", "dh"],
		aliases: ["rdx", "edx", "dx", "dl", "dh"],
	},
	ebx: {
		name: "ebx",
		size: 32,
		family: "rbx",
		encoding: 3,
		type: "gpr",
		parts: ["ebx", "bx", "bl", "bh"],
		aliases: ["rbx", "ebx", "bx", "bl", "bh"],
	},
	esp: {
		name: "esp",
		size: 32,
		family: "rsp",
		encoding: 4,
		type: "gpr",
		parts: ["esp", "sp", "spl"],
		aliases: ["rsp", "esp", "sp", "spl"],
	},
	ebp: {
		name: "ebp",
		size: 32,
		family: "rbp",
		encoding: 5,
		type: "gpr",
		parts: ["ebp", "bp", "bpl"],
		aliases: ["rbp", "ebp", "bp", "bpl"],
	},
	esi: {
		name: "esi",
		size: 32,
		family: "rsi",
		encoding: 6,
		type: "gpr",
		parts: ["esi", "si", "sil"],
		aliases: ["rsi", "esi", "si", "sil"],
	},
	edi: {
		name: "edi",
		size: 32,
		family: "rdi",
		encoding: 7,
		type: "gpr",
		parts: ["edi", "di", "dil"],
		aliases: ["rdi", "edi", "di", "dil"],
	},
	r8d: {
		name: "r8d",
		size: 32,
		family: "r8",
		encoding: 8,
		type: "gpr",
		parts: ["r8d", "r8w", "r8b"],
		aliases: ["r8", "r8d", "r8w", "r8b"],
	},
	r9d: {
		name: "r9d",
		size: 32,
		family: "r9",
		encoding: 9,
		type: "gpr",
		parts: ["r9d", "r9w", "r9b"],
		aliases: ["r9", "r9d", "r9w", "r9b"],
	},
	r10d: {
		name: "r10d",
		size: 32,
		family: "r10",
		encoding: 10,
		type: "gpr",
		parts: ["r10d", "r10w", "r10b"],
		aliases: ["r10", "r10d", "r10w", "r10b"],
	},
	r11d: {
		name: "r11d",
		size: 32,
		family: "r11",
		encoding: 11,
		type: "gpr",
		parts: ["r11d", "r11w", "r11b"],
		aliases: ["r11", "r11d", "r11w", "r11b"],
	},
	r12d: {
		name: "r12d",
		size: 32,
		family: "r12",
		encoding: 12,
		type: "gpr",
		parts: ["r12d", "r12w", "r12b"],
		aliases: ["r12", "r12d", "r12w", "r12b"],
	},
	r13d: {
		name: "r13d",
		size: 32,
		family: "r13",
		encoding: 13,
		type: "gpr",
		parts: ["r13d", "r13w", "r13b"],
		aliases: ["r13", "r13d", "r13w", "r13b"],
	},
	r14d: {
		name: "r14d",
		size: 32,
		family: "r14",
		encoding: 14,
		type: "gpr",
		parts: ["r14d", "r14w", "r14b"],
		aliases: ["r14", "r14d", "r14w", "r14b"],
	},
	r15d: {
		name: "r15d",
		size: 32,
		family: "r15",
		encoding: 15,
		type: "gpr",
		parts: ["r15d", "r15w", "r15b"],
		aliases: ["r15", "r15d", "r15w", "r15b"],
	},
	// 16-bit views
	ax: {
		name: "ax",
		size: 16,
		family: "rax",
		encoding: 0,
		type: "gpr",
		parts: ["ax", "al", "ah"],
		aliases: ["rax", "eax", "ax", "al", "ah"],
	},
	cx: {
		name: "cx",
		size: 16,
		family: "rcx",
		encoding: 1,
		type: "gpr",
		parts: ["cx", "cl", "ch"],
		aliases: ["rcx", "ecx", "cx", "cl", "ch"],
	},
	dx: {
		name: "dx",
		size: 16,
		family: "rdx",
		encoding: 2,
		type: "gpr",
		parts: ["dx", "dl", "dh"],
		aliases: ["rdx", "edx", "dx", "dl", "dh"],
	},
	bx: {
		name: "bx",
		size: 16,
		family: "rbx",
		encoding: 3,
		type: "gpr",
		parts: ["bx", "bl", "bh"],
		aliases: ["rbx", "ebx", "bx", "bl", "bh"],
	},
	sp: {
		name: "sp",
		size: 16,
		family: "rsp",
		encoding: 4,
		type: "gpr",
		parts: ["sp"],
		aliases: ["rsp", "esp", "sp", "spl"],
	},
	bp: {
		name: "bp",
		size: 16,
		family: "rbp",
		encoding: 5,
		type: "gpr",
		parts: ["bp"],
		aliases: ["rbp", "ebp", "bp", "bpl"],
	},
	si: {
		name: "si",
		size: 16,
		family: "rsi",
		encoding: 6,
		type: "gpr",
		parts: ["si"],
		aliases: ["rsi", "esi", "si", "sil"],
	},
	di: {
		name: "di",
		size: 16,
		family: "rdi",
		encoding: 7,
		type: "gpr",
		parts: ["di"],
		aliases: ["rdi", "edi", "di", "dil"],
	},
	r8w: {
		name: "r8w",
		size: 16,
		family: "r8",
		encoding: 8,
		type: "gpr",
		parts: ["r8w", "r8b"],
		aliases: ["r8", "r8d", "r8w", "r8b"],
	},
	r9w: {
		name: "r9w",
		size: 16,
		family: "r9",
		encoding: 9,
		type: "gpr",
		parts: ["r9w", "r9b"],
		aliases: ["r9", "r9d", "r9w", "r9b"],
	},
	r10w: {
		name: "r10w",
		size: 16,
		family: "r10",
		encoding: 10,
		type: "gpr",
		parts: ["r10w", "r10b"],
		aliases: ["r10", "r10d", "r10w", "r10b"],
	},
	r11w: {
		name: "r11w",
		size: 16,
		family: "r11",
		encoding: 11,
		type: "gpr",
		parts: ["r11w", "r11b"],
		aliases: ["r11", "r11d", "r11w", "r11b"],
	},
	r12w: {
		name: "r12w",
		size: 16,
		family: "r12",
		encoding: 12,
		type: "gpr",
		parts: ["r12w", "r12b"],
		aliases: ["r12", "r12d", "r12w", "r12b"],
	},
	r13w: {
		name: "r13w",
		size: 16,
		family: "r13",
		encoding: 13,
		type: "gpr",
		parts: ["r13w", "r13b"],
		aliases: ["r13", "r13d", "r13w", "r13b"],
	},
	r14w: {
		name: "r14w",
		size: 16,
		family: "r14",
		encoding: 14,
		type: "gpr",
		parts: ["r14w", "r14b"],
		aliases: ["r14", "r14d", "r14w", "r14b"],
	},
	r15w: {
		name: "r15w",
		size: 16,
		family: "r15",
		encoding: 15,
		type: "gpr",
		parts: ["r15w", "r15b"],
		aliases: ["r15", "r15d", "r15w", "r15b"],
	},
	// 8-bit low
	al: {
		name: "al",
		size: 8,
		family: "rax",
		encoding: 0,
		type: "gpr",
		parts: ["al"],
		aliases: ["rax", "eax", "ax", "al", "ah"],
	},
	cl: {
		name: "cl",
		size: 8,
		family: "rcx",
		encoding: 1,
		type: "gpr",
		parts: ["cl"],
		aliases: ["rcx", "ecx", "cx", "cl", "ch"],
	},
	dl: {
		name: "dl",
		size: 8,
		family: "rdx",
		encoding: 2,
		type: "gpr",
		parts: ["dl"],
		aliases: ["rdx", "edx", "dx", "dl", "dh"],
	},
	bl: {
		name: "bl",
		size: 8,
		family: "rbx",
		encoding: 3,
		type: "gpr",
		parts: ["bl"],
		aliases: ["rbx", "ebx", "bx", "bl", "bh"],
	},
	spl: {
		name: "spl",
		size: 8,
		family: "rsp",
		encoding: 4,
		type: "gpr",
		parts: ["spl"],
		aliases: ["rsp", "esp", "sp", "spl"],
	},
	bpl: {
		name: "bpl",
		size: 8,
		family: "rbp",
		encoding: 5,
		type: "gpr",
		parts: ["bpl"],
		aliases: ["rbp", "ebp", "bp", "bpl"],
	},
	sil: {
		name: "sil",
		size: 8,
		family: "rsi",
		encoding: 6,
		type: "gpr",
		parts: ["sil"],
		aliases: ["rsi", "esi", "si", "sil"],
	},
	dil: {
		name: "dil",
		size: 8,
		family: "rdi",
		encoding: 7,
		type: "gpr",
		parts: ["dil"],
		aliases: ["rdi", "edi", "di", "dil"],
	},
	r8b: {
		name: "r8b",
		size: 8,
		family: "r8",
		encoding: 8,
		type: "gpr",
		parts: ["r8b"],
		aliases: ["r8", "r8d", "r8w", "r8b"],
	},
	r9b: {
		name: "r9b",
		size: 8,
		family: "r9",
		encoding: 9,
		type: "gpr",
		parts: ["r9b"],
		aliases: ["r9", "r9d", "r9w", "r9b"],
	},
	r10b: {
		name: "r10b",
		size: 8,
		family: "r10",
		encoding: 10,
		type: "gpr",
		parts: ["r10b"],
		aliases: ["r10", "r10d", "r10w", "r10b"],
	},
	r11b: {
		name: "r11b",
		size: 8,
		family: "r11",
		encoding: 11,
		type: "gpr",
		parts: ["r11b"],
		aliases: ["r11", "r11d", "r11w", "r11b"],
	},
	r12b: {
		name: "r12b",
		size: 8,
		family: "r12",
		encoding: 12,
		type: "gpr",
		parts: ["r12b"],
		aliases: ["r12", "r12d", "r12w", "r12b"],
	},
	r13b: {
		name: "r13b",
		size: 8,
		family: "r13",
		encoding: 13,
		type: "gpr",
		parts: ["r13b"],
		aliases: ["r13", "r13d", "r13w", "r13b"],
	},
	r14b: {
		name: "r14b",
		size: 8,
		family: "r14",
		encoding: 14,
		type: "gpr",
		parts: ["r14b"],
		aliases: ["r14", "r14d", "r14w", "r14b"],
	},
	r15b: {
		name: "r15b",
		size: 8,
		family: "r15",
		encoding: 15,
		type: "gpr",
		parts: ["r15b"],
		aliases: ["r15", "r15d", "r15w", "r15b"],
	},
	// 8-bit high (legacy)
	ah: {
		name: "ah",
		size: 8,
		family: "rax",
		encoding: 4,
		type: "gpr",
		parts: ["ah"],
		aliases: ["rax", "eax", "ax", "al", "ah"],
	},
	ch: {
		name: "ch",
		size: 8,
		family: "rcx",
		encoding: 5,
		type: "gpr",
		parts: ["ch"],
		aliases: ["rcx", "ecx", "cx", "cl", "ch"],
	},
	dh: {
		name: "dh",
		size: 8,
		family: "rdx",
		encoding: 6,
		type: "gpr",
		parts: ["dh"],
		aliases: ["rdx", "edx", "dx", "dl", "dh"],
	},
	bh: {
		name: "bh",
		size: 8,
		family: "rbx",
		encoding: 7,
		type: "gpr",
		parts: ["bh"],
		aliases: ["rbx", "ebx", "bx", "bl", "bh"],
	},
	// Segment registers
	cs: {
		name: "cs",
		size: 16,
		family: "cs",
		encoding: 1,
		type: "segment",
		aliases: ["cs"],
	},
	ds: {
		name: "ds",
		size: 16,
		family: "ds",
		encoding: 3,
		type: "segment",
		aliases: ["ds"],
	},
	es: {
		name: "es",
		size: 16,
		family: "es",
		encoding: 0,
		type: "segment",
		aliases: ["es"],
	},
	fs: {
		name: "fs",
		size: 16,
		family: "fs",
		encoding: 4,
		type: "segment",
		aliases: ["fs"],
	},
	gs: {
		name: "gs",
		size: 16,
		family: "gs",
		encoding: 5,
		type: "segment",
		aliases: ["gs"],
	},
	ss: {
		name: "ss",
		size: 16,
		family: "ss",
		encoding: 2,
		type: "segment",
		aliases: ["ss"],
	},
	// Instruction pointer
	rip: {
		name: "rip",
		size: 64,
		family: "rip",
		encoding: 5,
		type: "ip",
		aliases: ["rip", "eip", "ip"],
	},
	eip: {
		name: "eip",
		size: 32,
		family: "rip",
		encoding: 5,
		type: "ip",
		aliases: ["rip", "eip", "ip"],
	},
	ip: {
		name: "ip",
		size: 16,
		family: "rip",
		encoding: 5,
		type: "ip",
		aliases: ["rip", "eip", "ip"],
	},
	// SIMD (representative entries)
	xmm0: {
		name: "xmm0",
		size: 128,
		family: "xmm0",
		encoding: 0,
		type: "xmm",
		aliases: ["xmm0", "ymm0", "zmm0"],
	},
	xmm1: {
		name: "xmm1",
		size: 128,
		family: "xmm1",
		encoding: 1,
		type: "xmm",
		aliases: ["xmm1", "ymm1", "zmm1"],
	},
	xmm2: {
		name: "xmm2",
		size: 128,
		family: "xmm2",
		encoding: 2,
		type: "xmm",
		aliases: ["xmm2", "ymm2", "zmm2"],
	},
	xmm3: {
		name: "xmm3",
		size: 128,
		family: "xmm3",
		encoding: 3,
		type: "xmm",
		aliases: ["xmm3", "ymm3", "zmm3"],
	},
	xmm4: {
		name: "xmm4",
		size: 128,
		family: "xmm4",
		encoding: 4,
		type: "xmm",
		aliases: ["xmm4", "ymm4", "zmm4"],
	},
	xmm5: {
		name: "xmm5",
		size: 128,
		family: "xmm5",
		encoding: 5,
		type: "xmm",
		aliases: ["xmm5", "ymm5", "zmm5"],
	},
	xmm6: {
		name: "xmm6",
		size: 128,
		family: "xmm6",
		encoding: 6,
		type: "xmm",
		aliases: ["xmm6", "ymm6", "zmm6"],
	},
	xmm7: {
		name: "xmm7",
		size: 128,
		family: "xmm7",
		encoding: 7,
		type: "xmm",
		aliases: ["xmm7", "ymm7", "zmm7"],
	},
	ymm0: {
		name: "ymm0",
		size: 256,
		family: "xmm0",
		encoding: 0,
		type: "ymm",
		aliases: ["xmm0", "ymm0", "zmm0"],
	},
	ymm1: {
		name: "ymm1",
		size: 256,
		family: "xmm1",
		encoding: 1,
		type: "ymm",
		aliases: ["xmm1", "ymm1", "zmm1"],
	},
	zmm0: {
		name: "zmm0",
		size: 512,
		family: "xmm0",
		encoding: 0,
		type: "zmm",
		aliases: ["xmm0", "ymm0", "zmm0"],
	},
	zmm1: {
		name: "zmm1",
		size: 512,
		family: "xmm1",
		encoding: 1,
		type: "zmm",
		aliases: ["xmm1", "ymm1", "zmm1"],
	},
	// MMX
	mm0: {
		name: "mm0",
		size: 64,
		family: "mm0",
		encoding: 0,
		type: "mmx",
		aliases: ["mm0"],
	},
	mm1: {
		name: "mm1",
		size: 64,
		family: "mm1",
		encoding: 1,
		type: "mmx",
		aliases: ["mm1"],
	},
	mm2: {
		name: "mm2",
		size: 64,
		family: "mm2",
		encoding: 2,
		type: "mmx",
		aliases: ["mm2"],
	},
	mm3: {
		name: "mm3",
		size: 64,
		family: "mm3",
		encoding: 3,
		type: "mmx",
		aliases: ["mm3"],
	},
	// x87 FPU
	st0: {
		name: "st0",
		size: 80,
		family: "st0",
		encoding: 0,
		type: "st",
		aliases: ["st0", "st"],
	},
	st1: {
		name: "st1",
		size: 80,
		family: "st1",
		encoding: 1,
		type: "st",
		aliases: ["st1"],
	},
	st: {
		name: "st",
		size: 80,
		family: "st0",
		encoding: 0,
		type: "st",
		aliases: ["st0", "st"],
	},
};

const BYTES_OF_REG: Record<number, string> = {
	8: "byte (1 byte)",
	16: "word (2 bytes)",
	32: "dword (4 bytes)",
	64: "qword (8 bytes)",
	128: "xmmword (16 bytes)",
	256: "ymmword (32 bytes)",
	512: "zmmword (64 bytes)",
	80: "tbyte (10 bytes)",
};

const schema = {
	action: z
		.enum(["reg_info", "reg_parts", "reg_aliases", "reg_size"])
		.describe("Action: reg_info | reg_parts | reg_aliases | reg_size"),
	register: z.string().describe("Register name (e.g. eax, rsp, xmm0, ah, cs)"),
};

const inputSchema = z.object(schema);
type Input = z.infer<typeof inputSchema>;

function lookup(name: string): RegInfo {
	const r = REGISTERS[name.toLowerCase()];
	if (!r) throw new Error(`Unknown register: ${name}`);
	return r;
}

export function execute(input: Input): string {
	const reg = lookup(input.register);

	switch (input.action) {
		case "reg_info":
			return JSON.stringify({
				name: reg.name,
				size: reg.size,
				bytes: reg.size / 8,
				sizeDescription: BYTES_OF_REG[reg.size] ?? `${reg.size} bits`,
				family: reg.family,
				encoding: reg.encoding,
				type: reg.type,
				parts: reg.parts ?? [reg.name],
				aliases: reg.aliases ?? [reg.name],
				highByte: reg.name.endsWith("h") && reg.size === 8,
				requiresREX: reg.encoding >= 8,
			});
		case "reg_parts":
			return JSON.stringify({
				register: reg.name,
				parts: reg.parts ?? [reg.name],
			});
		case "reg_aliases":
			return JSON.stringify({
				register: reg.name,
				aliases: reg.aliases ?? [reg.name],
				family: reg.family,
			});
		case "reg_size":
			return JSON.stringify({
				register: reg.name,
				size: reg.size,
				bytes: reg.size / 8,
				sizeDescription: BYTES_OF_REG[reg.size] ?? `${reg.size} bits`,
			});
		default:
			throw new Error(`Unknown action: ${input.action}`);
	}
}

export const tool: ToolDefinition = {
	name: "asm_registers",
	description:
		"x86/x64 register information for MASM/assembly: register size, byte count, encoding, family hierarchy (AL/AH/AX/EAX/RAX), sub-registers, and aliases. Covers GPRs, segment registers, XMM/YMM/ZMM, MMX, and x87 FPU registers.",
	schema,
	handler: async (args: Record<string, unknown>) => {
		const input = inputSchema.parse(args);
		return execute(input);
	},
};
